# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - qrway

on:
  push:
    branches:
      - containerize
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.5.0
        with:
          submodules: false

      - name: Set up Node.js version
        uses: actions/setup-node@v2.5.0
        with:
          node-version: '18.x'

      - name: Set Environment Variables
        run: |
          cd backend
          touch .env
          echo "ATLAS_URI=${{ secrets.ATLAS_URI }}" >> .env
          echo "GOOGLE_OAUTH_ID=${{ secrets.GOOGLE_OAUTH_ID }}" >> .env
          echo "GOOGLE_OAUTH_SECRET=${{ secrets.GOOGLE_OAUTH_SECRET }}" >> .env

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Install Angular Dependencies
        run: cd frontend && npm install

      - name: Install Backend Dependencies
        run: cd backend && npm install

      - name: Nuke DB
        run: |
          cd backend && npm run populate_db

      - name: Build Frontend and Backend
        run: |
          cd backend
          npm run build-frontend
          npm run build

      - name: Create artifact archive
        run: |
          cd backend
          zip -r node-app.zip .

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: ./backend/node-app.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Sign in to Azure 
        # Use the GitHub secret you added.
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'qrway'
          slot-name: 'Production'
          package: node-app.zip
      - name: Sign out of Azure.
        run: |
          az logout
